backend:
  name: git-gateway
  branch: main # ou master selon ton dépôt

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Articles"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Auteur", name: "author", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }
